ip_prefix: 10.10.10.
id: 1
peers:
  - 2

username: malte

enc_dir: enc
dec_dir: dec
fs_passphrase: xxx

dirs:
  documents: 
    # Watch for trailing slashes!
    path: Documents
    exclude:
      - "*/big/*"
      - "*.mp4"


debug: yes
logfile: /home/malte/log

