ip_prefix: 10.10.10.
id: 1
peers:
  - 2
  - 3

username: malte

enc_dir: encrypted
dec_dir: decrypted
ecryptfs_passphrase: v3ry_s3cr37

dirs:
  documents: 
    path: Documents
    exclude:
      - "*/big/*"
      - "*.mp4"


debug: no

